---
abstract: 'write-once attributes for Moo'
author:
  - 'haarg - Graham Knop (cpan:HAARG) <haarg@haarg.org>'
build_requires:
  Test::Fatal: '0'
  Test::More: '0.94'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MooX-SetOnce
no_index:
  directory:
    - t
    - inc
requires:
  Class::Method::Modifiers: '1.05'
  Moo: '1.002'
  perl: '5.008001'
  strictures: '1'
resources:
  repository: git://github.com/haarg/MooX-SetOnce.git
version: '0.001003'
